name: check
on: push
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configuration of Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'
      - name: Run app
        run: go run main.go
        working-directory: cmd/service

